# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"SecretSanta": "00_core.ipynb",
         "has_self_assignments": "01_lottery.ipynb",
         "get_assignemnts": "01_lottery.ipynb",
         "get_variables": "02_replace.ipynb",
         "replace_vars": "02_replace.ipynb",
         "create_html_message": "03_email.ipynb",
         "add_attachmet": "03_email.ipynb",
         "send_smtp_email": "03_email.ipynb",
         "CONFIG_FN": "04_constants.ipynb",
         "PARTICIPANTS_FN": "04_constants.ipynb",
         "REPLACEMENTS_FN": "04_constants.ipynb",
         "HTML_TPL_BASE_FN": "04_constants.ipynb",
         "RULES_FN": "04_constants.ipynb"}

modules = ["core.py",
           "lottery.py",
           "replace.py",
           "email.py",
           "constants.py"]

doc_url = "https://eandreas.github.io/secretsanta/"

git_url = "https://github.com/eandreas/secretsanta/tree/master/"

def custom_doc_links(name): return None
