# AUTOGENERATED! DO NOT EDIT! File to edit: 04_constants.ipynb (unless otherwise specified).

__all__ = ['CONFIG_FN', 'PARTICIPANTS_FN', 'REPLACEMENTS_FN', 'HTML_TPL_BASE_FN', 'RULES_FN']

# Cell
CONFIG_FN = 'config.ini'
PARTICIPANTS_FN = 'participants.csv'
REPLACEMENTS_FN = 'replacements.csv'
HTML_TPL_BASE_FN = 'html_template_'
RULES_FN = 'rules.ini'