# AUTOGENERATED! DO NOT EDIT! File to edit: 01_lottery.ipynb (unless otherwise specified).

__all__ = ['has_self_assignments', 'get_assignemnts']

# Cell
import pandas as pd
from pathlib2 import Path
import random

# Cell
def has_self_assignments(assignments):
    'Returns `True` in case the list of touples `assignments` does not contain a touple consisting of the same values.'
    for a in assignments:
        if (a[0] == a[1]):
            return True
    return False

# Cell
def get_assignemnts(li, allow_sa = False):
    '''Assigne each item of a list `li` an item of the same list and return these touples.
    In case of `allow_sa=False` self assignments are not allowed.'''
    li_ = li.copy()
    random.shuffle(li_)
    a = list(zip(li, li_))
    if not allow_sa:
        while(has_self_assignments(a)):
            a = get_assignemnts(li, allow_sa = True)
    return a